version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
  
  - package-ecosystem: "npm"
    directory: "/deps/promise-core/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
 
